### ISSUE TITLE
Regarding FuelEconomyObdCommand

### ISSUE THREAD

**Issue by PareshMayani** [pires/obd-java-api#102]
Hi,

First of all thank so much for writing OBD Api and Reader. You are awesome!

Now, I have got a project having FuelEconomyObdCommand and using old OBD Api. I have checked commit history and found out that you have removed this class. https://github.com/pires/obd-java-api/commit/558eb16ff9627e9012b70732f03078847c9ebd68

Could you please share more details it? Any replacement class available for the same?

Thanks,
Paresh Mayani

**Comment by pires** [comment]
Fuel consumption rate is never implemented by manufacturers. Having that class meant that I tried to somehow get valid data, but I never couldn't. I have removed everything related to fuel consumption.

**Comment by PareshMayani** [comment]
Thank you @pires for the quick reply. Really appreciate it!
