### ISSUE TITLE
Vehicle Identification Number (VIN)

### ISSUE THREAD

**Issue by pranaypatel512** [pires/obd-java-api#104]
Is there any command or code through which we can get [Vehicle Identification Number (VIN)](https://en.wikipedia.org/wiki/OBD-II_PIDs#Mode_09) ?

Thanks,
Pranay

**Comment by Ewg777** [comment]
@pranaypatel512 try VinCommand but VIN may be not available for some reason.
https://github.com/pires/obd-java-api/blob/master/src/main/java/com/github/pires/obd/commands/control/VinCommand.java

**Comment by pires** [comment]
Thank you @Ewg777.

**Comment by pranaypatel512** [comment]
@Ewg777  Thanks for suggesting command.
I got  Vehicle Identification Number using below code:
`if (cmdID.endsWith(AvailableCommandNames.VIN.toString())) { //cmdID = obdCommandJob.getCommand().getName();
                VinCommand command = (VinCommand) job.getCommand();
Log.e("COMMAND:", "VIN No:" + command.getFormattedResult());
}`

**O/P**
https://goo.gl/6Hv8lt
