### ISSUE TITLE
How to re-establish obd2 connection?

### ISSUE THREAD

**Issue by 410N50** [pires/obd-java-api#106]
Hi Paulo, I hope that you are fine.
I'm using your library in order to send OBD commands and receive the response. This process is working fine for me.
In my app, I need to check OBD responses always.
Below my question: 
How to re-establish obd2 connection (automatically) if vehicle turn off and then turn on?
Any suggestion?
Thanks in advanced.

**Comment by pires** [comment]
On your app code, you need to detect if the I/O streams are closed and reopen them. I'm not sure the ELM device is turned-off, though so this is just one idea.

**Comment by 410N50** [comment]
Hi Paulo,

ELM is not turn off though car is off.
How to detect if the I/O streams are closed and reopen them?
When car is off I am receiving NODATA in your fillerBuffer function.
Many thanks for your comments.

2016-04-28 3:31 GMT-05:00 Paulo Pires <notifications@github.com>:
