### ISSUE TITLE
PermanentTroubleCodesCommand.java not returning expected results

### ISSUE THREAD

**Issue by Pho3niX90** [pires/obd-java-api#108]
Hi,

I cannot get the mentioned class to return the correct information. I cannot find a lot of info about mode 10, but I have a feeling this has to do with the headers. I will do some tests tomorrow and revert back. However, it is returning a code where it shouldn't, and in hex.

**Comment by Pho3niX90** [comment]
rawData = 7F0A11
Calculated = C3F0A

This however is very intermittent. Still trying to figure out the correct way forward.

**Comment by Pho3niX90** [comment]
More info.
7F = general fail response.
11 = Service Not Supported.

@pires not sure if this should be handled in the library or the app iteself?

**Comment by pires** [comment]
Translation should happen at the app level.
