### ISSUE TITLE
Boolean protocol Commands

### ISSUE THREAD

**Issue by malvadeza** [pires/obd-java-api#120]
Hello there!

I actually don't know if this is the right way of reaching you about the development of the project, but here we go.

I know it sounds odd but, wouldn't be better if commands like ```EchoOffCommand``` ```HeadersOffCommand``` and ```LineFeedOffCommand``` had a possibility of re-enabling them?

I know that for most of the projects you just want to shut them all but what if some person (like me, but just for a tiny toy app) wanted to reactivate them?

It would be usefull if in the constructor you could send a boolean telling to go on/off.
As this is normally done in the setup it is usually just one line that would change and if you want it back again you just issue it.

What I am trying to say is that it probably wouldn't change much, but would allow the other way arround (i.e. ```EchoOnCommand```) without creating a new class.

I would be honored to contribute with it, if agreed.

Cheers.

**Comment by pires** [comment]
Hi @malvadeza. It's an interesting idea but unfortunately it would mean an API break. That said, you can open PRs for adding `{Echo,Line,Headers,etc.}OnCommand`. I'd be glad to review them.
