### ISSUE TITLE
Command to read odometer/mileage reading

### ISSUE THREAD

**Issue by vijquick** [pires/obd-java-api#132]
There should be a command to read the odometer current reading. Have browsed through the source code and couldn't find any command that can return the odometer reading. 

If the command is not supported is there a work around to achieve this?

**Comment by Odmink0** [comment]
OBDII protocols doesn't have milleage PID.

**Comment by alamirah93** [comment]
I working on project that should get the odometer/mileage reading!
how can I receive that ?

**Comment by Odmink0** [comment]
It is IMPOSSIBLE.
Please read about OBD PIDs(https://en.wikipedia.org/wiki/OBD-II_PIDs)

Maybe some auto vendors include odometer data in own protocol(or bus) but for reading that data you can't use ELM327 adapter.

obd-java-api only for ELM327 adapters.

**Comment by pires** [comment]
Thanks for explaining!

**Comment by alamirah93** [comment]
OK thank you for your answer, do you know another adapter that can read the odometer?

**Comment by Odmink0** [comment]
Main problem not in adapter.
In 95% autos milleage data stored in EEPROM chip which not connected to diagnostic bus.
This is made for security purposes.
