### ISSUE TITLE
Bad practice using generic exceptions

### ISSUE THREAD

**Issue by bbarnhill** [pires/obd-java-api#23]
...obd/commands/fuel/FindFuelTypeObdCommand.java

catches a generic Exception and a more specific exception should be caught, a blanket Exception catcher is usually a sign of swallowing exceptions that arent expected.

**Comment by pires** [comment]
Care to provide a PR with a possible fix?

**Comment by bbarnhill** [comment]
https://github.com/pires/obd-java-api/pull/31

**Comment by pires** [comment]
Fixed by #31
