### ISSUE TITLE
library returns '?' on every request 

### ISSUE THREAD

**Issue by skayred** [pires/obd-java-api#25]
Here is my code:

    socket = device.createInsecureRfcommSocketToServiceRecord(uuid);
    socket.connect();

    final CustomRPMCommand engineRpmCommand = new CustomRPMCommand();
    final SpeedObdCommand speedObdCommand = new SpeedObdCommand();
    while (!Thread.currentThread().isInterrupted()) {
        engineRpmCommand.run(socket.getInputStream(), socket.getOutputStream());
        speedObdCommand.run(socket.getInputStream(), socket.getOutputStream());

        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                speedometerGauge.setSpeed(engineRpmCommand.getRPM(), true);
                rpmGauge.setSpeed(speedObdCommand.getMetricSpeed(), true);
            }
        });
    }

What is wrong with my code?

**Comment by skayred** [comment]
I've copied OBD service from the sample application and it works!

**Comment by pires** [comment]
Awesome!
