### ISSUE TITLE
OBD ELM327 Device returning NODATA for every request

### ISSUE THREAD

**Issue by dnlgby** [pires/obd-java-api#58]
Before running any command, i run this init code:
       
        try {
            runCommand(sock, new ObdResetCommand());
            runCommand(sock, new EchoOffObdCommand());
            runCommand(sock, new EchoOffObdCommand());
            runCommand(sock, new LineFeedOffObdCommand());
            runCommand(sock, new TimeoutObdCommand(OBD_INIT_TIMEOUT_VAL));
            runCommand(sock, new SelectProtocolObdCommand(ObdProtocols.AUTO));
            runCommand(sock, new AmbientAirTemperatureObdCommand());

        } catch (Exception e)
        {
            throw new ObdConnectionFailure(e.getMessage());
        }

- OBD_INIT_TIMEOUT_VAL = 255

this code ends successfully, no exceptions.

after, i run some commands like:
SpeedObdCommand
EngineRPMObdCommand

And i always get NODATA as a result.
I have 3 different obd devices, tried them all. 

I have no idea what to try.

Thanks in advance.

**Comment by anti43** [comment]
your car bus is too slow probably. increase the command delay.

2015-08-01 21:52 GMT+02:00 dnlgby <notifications@github.com>:

**Comment by dnlgby** [comment]
thanks anty, but my timeout val is 255, the max val (one second).

**Comment by pires** [comment]
@dnlgby the value is in milliseconds.

**Comment by dnlgby** [comment]
when i work with obd terminals i get results, even if i set the timeout to 255.

**Comment by dnlgby** [comment]
Its not 255*4, 1020 milliseconds?

**Comment by anti43** [comment]
you misunderstood me probably. im not talking about the timeout val, its
the delay inside the ObdCommand class

2015-08-03 11:03 GMT+02:00 dnlgby <notifications@github.com>:

**Comment by dnlgby** [comment]
i see...
But i get response, 'NODATA'. as i see this time its only the time for the request thread to sleep.

**Comment by dnlgby** [comment]
changed ResponseTimeDelay to many values. same,

**Comment by dnlgby** [comment]
Another applications like torque working well...

**Comment by pires** [comment]
I have no idea why this happens.

**Comment by Pho3niX90** [comment]
Try removing the speed up part, and test.
https://github.com/pires/obd-java-api/blob/master/src/main/java/com/github/pires/obd/commands/ObdCommand.java#L44

**Comment by Pho3niX90** [comment]
Also what vehicle is it? I have noticed specifically diesel bmws have some issues with obd2.

**Comment by dnlgby** [comment]
Tried. still the same :(

My vehicle is seat leon fr 2014.

**Comment by FireWolf2007** [comment]
what is protocol used?
maximum data on ISO_15765_4_CAN.
Tested on VW Jetta 2013.

**Comment by Pho3niX90** [comment]
@pires was I correct in saying it was the speed up command?

**Comment by pires** [comment]
@Pho3niX90 seems so.

**Comment by dnlgby** [comment]
actually not. 

Log:
com.github.pires.obd.exceptions.NoDataException: Error running 01 2F, response: NODATA

**Comment by Pho3niX90** [comment]
@dnlgby seems it's only fuel level not working for you? It isn't supported by all cars. Not even toeque has it implemented. But try via a eln327 obd2 terminal

**Comment by dnlgby** [comment]
seems like you are right.
working well now.

Thank you!
