### ISSUE TITLE
Add more commands

### ISSUE THREAD

**Issue by pires** [pires/obd-java-api#59]
@mikes01, or anyone else for that matter (@anti43?), how about opening PRs to add some of the commands you're implementing on [your fork](https://github.com/mikes01/obd-java-api)? Would be glad to review them.

**Comment by PhilippGrulich** [comment]
That would be nice :+1:

**Comment by pires** [comment]
@valens254 is doing a great job here!

**Comment by Ewg777** [comment]
@pires Please add @valens254 as collaborator. Hi seems to be a nice collaborator.

**Comment by diegomalone** [comment]
Is there a way to send custom commands to the bluetooth adapter. If I want to get other commands not mapped and get the raw data read, is there a way?
