### ISSUE TITLE
RC8 release execute error on Windows 

### ISSUE THREAD

**Issue by Geraldo-Neto** [pires/obd-java-api#61]
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1

...while parsing com/github/pires/obd/commands/control/DistanceTraveledSinceCodesClearedCommand.class

A think this error is occuring on windows because of the huge-length name of this DistanceTraveledSinceCodesClearedCommand.class.

The Windows has a 260 character path length limit.

Please refactor it's name to a shorter one. e.g: DistTravSinCCCmd.class

Hope it helps!

**Comment by pires** [comment]
Yes, this has been identified by other users and I'm very glad to review a PR that fixes it.

**Comment by greatinfallible** [comment]
Ok, I will be wainting for the release.
Thank you!

**Comment by greatinfallible** [comment]
Pull request made.
