### ISSUE TITLE
ObdCommand issue

### ISSUE THREAD

**Issue by patrickSUP** [pires/obd-java-api#67]
Hi, 

I noticed that you added a speed up part which consists in adding " 1" after every command, this change causes NODATA response, I tried with 3 cars and it gave the same result. I'm using  OBDLink LX adapter. When I removed it everithing worked fine, can I ask with which setup this speedup works?
Here the part I'm referring to:
public ObdCommand(String command) {
        this.cmd = command;
        this.buffer = new ArrayList<Integer>();
        if (this instanceof ReturnAsapCommand) {
            this.cmd += " 1";//speed up 
        }
    }

**Comment by pires** [comment]
@anti43 I'm seeing a lot of users reporting this. Can you chime in and fix it if needed?

**Comment by anti43** [comment]
It maybe that not all adapters support it?

2015-09-14 16:12 GMT+02:00 Paulo Pires <notifications@github.com>:

**Comment by pires** [comment]
@anti43 can we make it optional somehow? Otherwise, I prefer to remove this functionality.

**Comment by anti43** [comment]
i think then you must remove it for now, until i found a way to detect the
ability of the adapter

2015-09-14 17:43 GMT+02:00 Paulo Pires <notifications@github.com>:
