### ISSUE TITLE
Delete DTC code

### ISSUE THREAD

**Issue by navat** [pires/obd-java-api#69]
Hi all, 

I was able to make all functions work on both simulator and real car except clearing the DTC code since I couldn't find the command to do.

You guys have any suggestion on how to delete the DTC code using the api.

Thank you in advance,

**Comment by sytolk** [comment]
Hi
I don\`t have success with DTC too but you have use https://github.com/pires/android-obd-reader application or ? And this simulator https://github.com/Hesamedin/ELM327#simulator-mode ?
I\`m trying to get (and clear) car distance traveled (kilometers) do you have success with this command ?

**Comment by Pho3niX90** [comment]
This is what you are looking for => https://github.com/pires/obd-java-api/blob/master/src/main/java/com/github/pires/obd/commands/protocol/ResetTroubleCodesCommand.java

I have had success with multiple cars. However, persistent/current codes that haven't been sorted will immediately trigger another error

**Comment by pires** [comment]
Thank you @Pho3niX90!
