### ISSUE TITLE
Can not to run OBD commands

### ISSUE THREAD

**Issue by 410N50** [pires/obd-java-api#78]
Hi Paulo,

Sorry for open new issue.
I have other issue with OBD command.
This is my code in Android Studio.

UUID uuid = UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");
BluetoothSocket socket = null;
BluetoothSocket tempsocket = null;

                                             try {
                                                 socket = device.createInsecureRfcommSocketToServiceRecord(uuid);
                                                 socket.connect();
                                                 Toast.makeText(getApplicationContext(), "Bluetooth conected", Toast.LENGTH_SHORT).show();
                                                 try {
                                                     new EchoOffCommand().run(socket.getInputStream(), socket.getOutputStream());
                                                     new LineFeedOffCommand().run(socket.getInputStream(),socket.getOutputStream());
                                                     new TimeoutCommand(125).run(socket.getInputStream(),socket.getOutputStream());
                                                     new SelectProtocolCommand(ObdProtocols.AUTO).run(socket.getInputStream(),socket.getOutputStream());
                                                     new AmbientAirTemperatureCommand().run(socket.getInputStream(),socket.getOutputStream());
                                                     Toast.makeText(getApplicationContext(),"OBD config finished" ,Toast.LENGTH_SHORT).show();
RPMCommand ComandoRPM = new RPMCommand();
                                                         while (!Thread.currentThread().isInterrupted()){
                                                             ComandoRPM.run(socket.getInputStream(),socket.getOutputStream());
                                                             Toast.makeText(getApplicationContext(),"Resultado comando RPM"+ComandoRPM ,Toast.LENGTH_SHORT).show();

                                                         }

                                                 }catch (Exception ex){
                                                     Toast.makeText(getApplicationContext(),"Can not to run OBD commands" ,Toast.LENGTH_SHORT).show();

                                                 }

                                             } catch (Exception e) {
                                                 // TODO Auto-generated catch block
                                                 e.printStackTrace();
                                                 Toast.makeText(getApplicationContext(), "Bluetooth error", Toast.LENGTH_SHORT).show();

                                             }
I tested in a car and socket connection is fine because I received the message "Bluetooth conected" but OBD configuration and OBD command is not running.beacuse Im receiving this message "Can not to run OBD commands".
Any suggestion?
Thanks in advanced.

**Comment by pires** [comment]
Print the exception stacktrace and you'll figure it out. I'm sorry but opening issues for debugging one's code is wrong. Use stackoverflow, email or then discussion groups.
