### ISSUE TITLE
Obd2 fault codes

### ISSUE THREAD

**Issue by xavierDesarrollo** [pires/obd-java-api#97]
Hi, OBD2 sends you fault codes, how I do to see these codes on android eclipse or what kind of class or method of obd_java_api can i to use???? please help me.

I need to connect to obd2 by bluetooth and get wathever fault code that obd2 throw me and show in my android.

**Comment by pranaypatel512** [comment]
Can you tried any code using obd_java_api?

**Comment by xavierDesarrollo** [comment]
hi pranaypatel, no i didn't.... please help me, how can i use thouse codes??

**Comment by Pho3niX90** [comment]
@xavierDesarrollo please have a look at https://github.com/pires/android-obd-reader for an android example. 
The classes you would use are 
https://github.com/pires/obd-java-api/blob/master/src/main/java/com/github/pires/obd/commands/control/TroubleCodesCommand.java
https://github.com/pires/obd-java-api/blob/master/src/main/java/com/github/pires/obd/commands/control/PendingTroubleCodesCommand.java
https://github.com/pires/obd-java-api/blob/master/src/main/java/com/github/pires/obd/commands/control/PermanentTroubleCodesCommand.java

**Comment by pires** [comment]
Thank you @Pho3niX90.
