### ISSUE TITLE
SpeedCommand always returning speed of 52 even when not moving

### ISSUE THREAD

**Issue by Abushawish** [pires/obd-java-api#98]
Using ELM327. I think it may have something to do with the hex code that's being returned/parsed incorrectly. Thoughts?

**Comment by pires** [comment]
Probably some protocol issue.

**Comment by frandrago** [comment]
Hi, I do not know how to write in Inglés, but I am going to try.

I have the same problem, you've found the solution?

Thank you!!

**Comment by frandrago** [comment]
I have this problem when I use the Bluetooth ELM327 V2.1 ODBII.
With earlier versions do not have this problem.

**Comment by Pho3niX90** [comment]
@Abushawish @frandrago 
Could you please supply your rawData value? 

Easiest to do the above is edit the SpeedCommand.java
`public String getCalculatedResult() {
        //return useImperialUnits ? String.valueOf(getImperialUnit()) : String.valueOf(getMetricSpeed());
        return rawData
    }`

**Comment by phamels** [comment]
@Pho3niX90 

Had the same issue using android-obd-reader (which uses obd-java-api)
The speed was displayed as a constant 65km/h while standing still and engine RPM of 4163.
Also the runtime was a constant 04:37:51.

A similar application (not to use any names) uses the protocol ISO15765-4CAN11/500 on this car & adapter combination but returns the data just fine.

Included the obd-java-api into the android-obd-reader project and changed the getCalculatedResult() to return the rawData though that didn't change anything to the data being displayed on the android-obd-reader app.

Anything I can do to test / help / give more data / results?

**Comment by Pho3niX90** [comment]
@phamels the library does not support the can protocol properly. So that would be your reason, however hopefully in the next month it will ;)

**Comment by pires** [comment]
@pho3nix90 that would be truly amazing.

**Comment by phamels** [comment]
@Pho3niX90 aha ok, expected it would be something like that :-) that would be awesome :-) This is my first dive into the OBD protocols but if there's anything I could do to provide feedback or help in any way, let me know!

**Comment by Pho3niX90** [comment]
Thanks for the offer, it is taking longer than I initially anticipated, since all my vehicles are K-LINE, and cannot find a simulator that communicates solely in CAN. Thus making testing difficult. I will post a pull request for the speed command first to make sure it works for everyone.

**Comment by Pho3niX90** [comment]
@phamels if you could do me a favour though, if you could install a obd2 terminal app on your phone, and send a command to the OBD2 adapter, could you please post the response from the vehicle up?+

**Comment by phamels** [comment]
@Pho3niX90 was actually already preparing my laptop as you wrote this to do this :-) heading down to the garage as we speak to to that for you :-)

**Comment by phamels** [comment]
@Pho3niX90 as promised:


TeraTerm: 

`
>ATI
ELM327 v2.1
>ATZ
ELM327 v2.1
>ATSP6
OK
>ATMA
STOPPED
>ATCS
T:00 R:00 
>ATRV
11.2V
>STI
?
>0100
41 00 BE 3E A8 13 
>011c
41 1C 06`

Android OBD Terminal:

`
> ATZ
ATZ

ELM327 v2.1

> ATH1
ATH1
OK

> ATDP
ATDP
ISO 15765-4 (CAN 11/500)

> ATMA
ATMA
STOPPED

> 010D
010D
7E8 03 41 0D 00 

> 010C
010C
7E8 04 41 0C 00 00 

> 010C
010C
7E8 04 41 0C 0A A0 

> 010C
010C
7E8 04 41 0C 0A 88 

> 010C
010C
7E8 04 41 0C 0A B4 
`

ATMA doesn't seem to return much data, neither on the android terminal or on the TeraTerm using windows

**Comment by Pho3niX90** [comment]
Was your RPM around 685?

**Comment by phamels** [comment]
Pretty sure it should be around there as I was just idling

**Comment by Pho3niX90** [comment]
OKay. Could you please try that again for me. 

First turn off the headers
ATH0

Then do RPM
010C

**Comment by phamels** [comment]
I'll go down in a minute to do that and take note of the RPM on the dash while doing it :-)

**Comment by Pho3niX90** [comment]
Thank you! Also, which vehicle are you testing this in, and which country?

**Comment by phamels** [comment]
My pleasure! Currently doing it on a 2010 Skoda Yeti (Imported it from Belgium; now doing it/living in Sofia, Bulgaria) (also have a BMW 640d available as well for dumping if required)

**Comment by Pho3niX90** [comment]
Awesome thanks. The API should work flawlessly with the 640d, unless it's a 2008+ model, then can might become an issue. However, as far as I know the ECU stayed the same for the E63 up until 2010

**Comment by phamels** [comment]
This one is a F13 :-) could do some tests on that as well :-) Heading down now to do a dump

**Comment by Pho3niX90** [comment]
Thanks, yeah F13 might be a problem. Would be great if you can do tests on it. And we can fix both in one go. The N57D30 is a brilliant engine.

**Comment by phamels** [comment]
In the car right now :-)

First engine off; then on at idle and at the last few tried to keep it around 1000rpm give or take a little:

>> 010C
010C
41 0C 00 00 

>> 010c
010c
41 0C 0A B8 

>> 010c
010c
41 0C 0A 78 

>> 010c
010c
41 0C 0F BC 

>> 010c
010c
41 0C 10 54 

>> 010c
010c
41 0C 10 A4 

>> 010c
010c
41 0C 10 8C 



I'll check for the F13 as well asap (not in the garage right now :-))

**Comment by Pho3niX90** [comment]
Hmm strange, from those results the library should work perfectly.
Have you tried the latest build of the app?

**Comment by phamels** [comment]
Seems to be correct; as far as I've been studying the output: 
PID 0C which returns RPM in this case 10 8C converted to decimal 4236 divided by four returns 1059 RPM; correct?

**Comment by phamels** [comment]
Yeah I have, compiled the source yesterday

**Comment by Pho3niX90** [comment]
The equation is as follows:
So output is: 
010c
41 0C 10 8C

410C gets removed, since it's just an echo of the command sent, you are left with 2 bytes, 10 and 8C, converted
10 = 16
8C = 140

Full equation is = (A * 256 + B) / 4  = 1059.

**Comment by Pho3niX90** [comment]
OKay could you set the protocol in the app to KWP, as a test

**Comment by Pho3niX90** [comment]
I think what is happening is the following. The terminals are infact not setting to automatic but hardcoding the protocol to some kline protocol, thus the vehicle is responding in the same manner. Where the app is by default on AUTO and the car is expecting CAN messages. This however is just a theory

**Comment by phamels** [comment]
Aha, thanks for the clarification on that! Just started my exploration into all of this since yesterday :-)

I'll do that, head down and come back with the results!
I tried yesterday using AUTO and ISO_15765_4_CAN with same results.
I'll try the ISO_14230_4_KWP now and perhaps a few others as well as a matter of testing

**Comment by Pho3niX90** [comment]
Yes that would be great. Any of the protocols that do not contain CAN. 
I will still however try and get the CAN working, since it is a way faster protocol.

**Comment by phamels** [comment]
Damn, KWP displays all data correctly! How could I have missed trying that! I will try to do some testing on the F13 though asap

**Comment by phamels** [comment]
Oh, can try with the F13 now if you like? What could I dump for you?

**Comment by phamels** [comment]
Weird, tried again now and getting businit error using kwp and the errorous values with can

**Comment by Pho3niX90** [comment]
Hmm strange. I think the app is sending the commands too fast. Plug out the adapter and back in, en check if you can modify the sleep time in the settings to something a little but higher, you could try one of the other non CAN protocols as well. Yes if you can send the same test scenarios for the F13 that would be great.

**Comment by Pho3niX90** [comment]
When you received the businit error, was it via the android compiled app or your own app?

**Comment by phamels** [comment]
The Businit error was with the android compiled app which was working earlier.
Tried different protocols again, ATZ command then trying it, restarting the phone even just to be sure :-) but now kept receiving protocol error where it was working before, strange indeed :-)
Also tried the F13; actually just gives the exact same values and uses the exact same protocol as the Skoda Yeti :-)

**Comment by Pho3niX90** [comment]
That is strange. And if you go back to the terminal after the app give you a buss error, does it still bring back results?

**Comment by phamels** [comment]
it is strange indeed, yeah it actually does when I try to use the terminal after the app.
Going to look more into it this evening and see what's going on there

**Comment by Pho3niX90** [comment]
Okay great. Will have a look on my side as well what would cause the error in the interim, until I can get a working version of the CAN protocol.

**Comment by phamels** [comment]
Can't get it to work on KWP at all anymore. Not in the app, not on terminal (also get the bus errors there using atsp4 and trying to fetch data)

**Comment by phamels** [comment]
Didn't test it before though with atsp4 on terminal, only atsp6. Kind of weird however i got the app to display correct data before with kwp including VIN number and all

**Comment by Pho3niX90** [comment]
I am going to implement a tester in my app to try all protocols from 1 to 7 to automatically find the correct protocol, instead of leaving it to the hardware. I eill uploaf the apk here for you to test if that is okay? If all is well I will do a PR.

**Comment by phamels** [comment]
sounds good! pretty much went through all the protocols in the terminal; the one that worked for me was number 6 (using the AT command to select the protocol 6 (ATSP6) or the auto one (ATSP0)) the rest threw up bus errors.

**Comment by Pho3niX90** [comment]
and on protocol 6, does it return in the same format you posted results earlier?

**Comment by phamels** [comment]
Yeah, that's what it did all along; it only gave me that output on the CAN protocol.
I'm still puzzled why it even worked on the KWP in the app :-)

**Comment by Pho3niX90** [comment]
Hmm weird. And when you set the app to protocol 6, and then try to read data what does it do?

**Comment by Pho3niX90** [comment]
@phamels 
Could you try this one on the vehicle? It uses the same library that has been modified to pass Parcels. 
However, it's a highly modified version of the original android project, and have also included to display the raw responses from the vehicle in the logcat, that will help diagnose why you are getting the errors. 

[Hazmat-Reader-debug-0.8.0.zip](https://github.com/pires/obd-java-api/files/267866/Hazmat-Reader-debug-0.8.0.zip)

**Comment by phamels** [comment]
When I set it to protocol 6 (or ISO_15765_4_CAN) in the app; I get the wrong values; as in a fixed speed of 65km/h at 4163RPM with a fixed trip time of 04:37:51 and a vehicle VIN with funky chars :-)

I'll go ahead and tre APK you attached!

**Comment by Pho3niX90** [comment]
Okay thank you, that would explain what is happening if you can extract the logcat.

**Comment by phamels** [comment]
Logs have been mailed!

**Comment by Pho3niX90** [comment]
Thank you! I think we might have caught the error. 

Are all 4 logs  from the same vehicle? 
It seems like the adapter is returning an echo of the command being sent. I am going to add a fix now

**Comment by phamels** [comment]
No, thank you! 
yes they are all from the same vehicle :-) I just tried different settings and one was trying to do error code check but that just crashed the app completely :-)

**Comment by Pho3niX90** [comment]
Examples that the vehicle/adapter returned:
Long Term Fuel Trim Bank 1: Calc = -49.2% | Raw = **0107 41 07 80**
So what is happening above is that it's echoing back the command, and adding the header. 
0107 is the command that was sent
4107 is the command that was sent
80 is the actual value.

So the value should have been 0%, meaning the car had to make no adjustments to the fueling, which is correct for a car idling. 


BUT. The app assumes the headers are turned of because we told the adapter to do so, however, it did not. Thus the app is using the 41 as the value, where it should have used 80 as the value. 

I hope that makes sense? 


Here  are more examples:
Engine Runtime: Calc = 04:37:51 | Raw = **011F 411F 0000**
Engine runtime has never worked for me.
 
Throttle Position: Calc = 25.5% | Raw = **0111 4111 2B**
Should have been 16.8, most manufacturers report around 16% for throttle on idle, and 85% at WOT.

**Comment by Pho3niX90** [comment]
Here is the weird part, the adapter reported that it did infact turn of the headers, however, it did not , see below:
D/CMDTEST (23691): Headers disabled: Calc = **ATH0OK** | Raw = ATH0OK **<- Reporting back header of ATH, should have been OK only** 
D/CMDTEST (23691): Adaptive timing set: Calc = **ATAT1OK** | Raw = ATAT1OK **Still sending header of ATAT1, should have been OK only**

**Comment by phamels** [comment]
aha yes, that does make sense :-) hmm, I'll have to look into the adapter in that case, because at one point when it was working, it actually did turn off the headers as it reported correct data then...
Though I did try to reset it manually etc, I can do some terminal tests to see if I can make it stop echoing

**Comment by phamels** [comment]
Well, that or modify the library and see if it is replying with the headers and then just strip them

**Comment by Pho3niX90** [comment]
Yes I am adding a check to strip data, to make sure it accounts for the different adapters. 

Give me about 30mins and will have a working test.

**Comment by phamels** [comment]
Was able to actually turn off the echo and stop the headers with the terminal; though did notice something when running the app.Where it expects the output for: Reset OBD: it replies with: +CONNECTING
Where it expects the Echo Off: it returns: ATZELM327v2.1
Then where it says: Line Feed Off: it receives ATL0OK

So I'm suspecting that it's not waiting long enough or just seeing the +CONNECTING and ATZELM327v2.1 or reply from the adapters first connection as OK's for the issued commands to turn off the echo and headers and those commands actually are not processed as it is still connecting...

Could that be?

**Comment by phamels** [comment]
I think it's exactly that as where in the "Echo Off:" It returns runs ATZ and the adapter replies with ELM327v2.1 where it should have been sending ATE0 and expecting "OK" as a reply, no?

**Comment by Pho3niX90** [comment]
That wad my initial though as well. But you will see from the logs you sent me that it did reply OK to the headers off comand, however the command thereafter it still sent the headers.

**Comment by phamels** [comment]
aha ok, was just a thought :) browsing through the code as well now, which I should have done before, to see where it does that init sequence etc

**Comment by Pho3niX90** [comment]
Okay I think your theory might be spot on, it's not actually the headers causing the issue, but echo'ing that caused it. So either there must be a sleep after resetting the adapter, or the echo's need to be stripped. 

Please give this one a shot, it is actually doing both of the above. 

@pires what do you suggest? Strip the echos out in code? Or handle it in the app?

[Hazmat-Reader-release-0.8.1.zip](https://github.com/pires/obd-java-api/files/269047/Hazmat-Reader-release-0.8.1.zip)

**Comment by phamels** [comment]
Okidoki, going to head down to the garage and try that
Also made a quick and dirty button in the app to send the EchoOffCommand and HeadersOffCommand for testing purposes :-)

**Comment by phamels** [comment]
Bingo! Sent you the log, readings are correct now!

**Comment by phamels** [comment]
Think it has to do with the initial response received as atz returns the adapter name where it thinks it receives the ok dor echo off

**Comment by Pho3niX90** [comment]
Awesome. Yes it seems it's def the initial response. The issue was fixed before stripping began, I added a thread sleep after the reset of 1000ms, and that solved it. The question just now is where this should be catered for, it seems it should be app specific.

**Comment by phamels** [comment]
I'm thinking app specific then, I could be wrong though, but doesn't the app do the connection sequence and then sends the echo off etc commands?
Or does the library handle the connection and contain the sleep in there since there's probably more adapters out there that will have this behavior?
Just dropping thoughts here, I'm not an expert java developer (I'm a web developer) and just learning as we speak as Android apps became a big interest for me :-)

**Comment by Pho3niX90** [comment]
Yes the app send the commands. If the correction is done within the library it would render the Echo command redundant and useless for the library. 
The library handles no connections, as it is a java library there is no 1 method for all intended platforms. 
But thanks for all you help, would not have solved this without you.

**Comment by phamels** [comment]
You're welcome! Thanks for that commit!
Glad we could get this sorted and thanks for giving me more insight into the whole code and the way this works, it's been an awesome learning experience (both this code and understanding the OBD protocol) !

**Comment by pires** [comment]
@Pho3niX90 so it's an app issue and I can close this, right?

**Comment by Pho3niX90** [comment]
@pires Yes correct, it seems that as @phamels pointed out that the app processes startup commands too fast after the reset, some adapters seem to take longer to reset than others. That is why we are seeing the unexplained issues. Also, going forward it seems that the library is handling CAN connections perfectly, and does  infact support it, however, will improve it as CAN has it's own method of sending and receiving messages for faster response. 

@phamels only a pleasure.

**Comment by pires** [comment]
Thank you @Pho3niX90.
